# Generated by Django 3.0.7 on 2020-06-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='imageuploadmodel',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='images/'),
        ),
    ]
